# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.
#
# Pydantic v2 exposes its public API through PEP 562 `__getattr__` plus a
# `_dynamic_imports` table in `pydantic/__init__.py`. Lifeguard cannot follow
# `__getattr__` dispatch, so without this stub every `pydantic.Field(...)`,
# `pydantic.ConfigDict(...)`, `@pydantic.field_serializer(...)`, etc. used at
# module/class-body scope is reported as `UnknownFunctionCall` /
# `UnknownDecoratorCall`.
#
# The declarations below mirror `pydantic.__all__` so the stub does not regress
# any name that callers reach via `pydantic.X` — submodules under pydantic
# (e.g. `pydantic.fields`, `pydantic.dataclasses`) are unaffected because this
# stub only overrides `pydantic/__init__.py`.
#
# Functions/decorators get `no_effects()` because they are pure constructors
# (Field/PrivateAttr/ConfigDict produce descriptor or TypedDict objects),
# decorator factories (field_serializer/model_validator/...), or constraint
# factories (conint/conlist/...). Pydantic does no module-load side effects
# from these calls — schema construction happens lazily on first model
# instantiation, not at import time.

from . import dataclasses

# functional validators
def field_validator(*args, **kwargs): no_effects()
def model_validator(*args, **kwargs): no_effects()
def root_validator(*args, **kwargs): no_effects()
def validator(*args, **kwargs): no_effects()

class AfterValidator: ...
class BeforeValidator: ...
class PlainValidator: ...
class WrapValidator: ...
class SkipValidation: ...
class ValidateAs: ...
class InstanceOf: ...
class ModelWrapValidatorHandler: ...

# JSON Schema
class WithJsonSchema: ...

# functional serializers
def field_serializer(*args, **kwargs): no_effects()
def model_serializer(*args, **kwargs): no_effects()

class PlainSerializer: ...
class SerializeAsAny: ...
class WrapSerializer: ...

# config
def ConfigDict(*args, **kwargs): no_effects()
def with_config(*args, **kwargs): no_effects()

class BaseConfig: ...
class Extra: ...

# validate_call
def validate_call(*args, **kwargs): no_effects()

# errors
class PydanticErrorCodes: ...
class PydanticUserError(Exception): ...
class PydanticSchemaGenerationError(Exception): ...
class PydanticImportError(Exception): ...
class PydanticUndefinedAnnotation(Exception): ...
class PydanticInvalidForJsonSchema(Exception): ...
class PydanticForbiddenQualifier(Exception): ...

# fields
def Field(*args, **kwargs): no_effects()
def computed_field(*args, **kwargs): no_effects()
def PrivateAttr(*args, **kwargs): no_effects()

# alias
class AliasChoices: ...
class AliasGenerator: ...
class AliasPath: ...

# main
class BaseModel: ...
def create_model(*args, **kwargs): no_effects()

# network
class AnyUrl: ...
class AnyHttpUrl: ...
class FileUrl: ...
class HttpUrl: ...
class FtpUrl: ...
class WebsocketUrl: ...
class AnyWebsocketUrl: ...
class UrlConstraints: ...
class EmailStr: ...
class NameEmail: ...
class IPvAnyAddress: ...
class IPvAnyInterface: ...
class IPvAnyNetwork: ...
class PostgresDsn: ...
class CockroachDsn: ...
class AmqpDsn: ...
class RedisDsn: ...
class MongoDsn: ...
class KafkaDsn: ...
class NatsDsn: ...
class MySQLDsn: ...
class MariaDBDsn: ...
class ClickHouseDsn: ...
class SnowflakeDsn: ...
def validate_email(*args, **kwargs): no_effects()

# root_model
class RootModel: ...

# deprecated tools
def parse_obj_as(*args, **kwargs): no_effects()
def schema_of(*args, **kwargs): no_effects()
def schema_json_of(*args, **kwargs): no_effects()

# types
class Strict: ...
class StrictStr: ...
def conbytes(*args, **kwargs): no_effects()
def conlist(*args, **kwargs): no_effects()
def conset(*args, **kwargs): no_effects()
def confrozenset(*args, **kwargs): no_effects()
def constr(*args, **kwargs): no_effects()
class StringConstraints: ...
class ImportString: ...
def conint(*args, **kwargs): no_effects()
class PositiveInt: ...
class NegativeInt: ...
class NonNegativeInt: ...
class NonPositiveInt: ...
def confloat(*args, **kwargs): no_effects()
class PositiveFloat: ...
class NegativeFloat: ...
class NonNegativeFloat: ...
class NonPositiveFloat: ...
class FiniteFloat: ...
def condecimal(*args, **kwargs): no_effects()
def condate(*args, **kwargs): no_effects()
class UUID1: ...
class UUID3: ...
class UUID4: ...
class UUID5: ...
class UUID6: ...
class UUID7: ...
class UUID8: ...
class FilePath: ...
class DirectoryPath: ...
class NewPath: ...
class Json: ...
class Secret: ...
class SecretStr: ...
class SecretBytes: ...
class SocketPath: ...
class StrictBool: ...
class StrictBytes: ...
class StrictInt: ...
class StrictFloat: ...
class PaymentCardNumber: ...
class ByteSize: ...
class PastDate: ...
class FutureDate: ...
class PastDatetime: ...
class FutureDatetime: ...
class AwareDatetime: ...
class NaiveDatetime: ...
class AllowInfNan: ...
class EncoderProtocol: ...
class EncodedBytes: ...
class EncodedStr: ...
class Base64Encoder: ...
class Base64Bytes: ...
class Base64Str: ...
class Base64UrlBytes: ...
class Base64UrlStr: ...
class GetPydanticSchema: ...
class Tag: ...
class Discriminator: ...
class JsonValue: ...
class FailFast: ...

# type_adapter
class TypeAdapter: ...

# version
__version__: str
VERSION: str

# warnings
class PydanticDeprecatedSince20(DeprecationWarning): ...
class PydanticDeprecatedSince26(DeprecationWarning): ...
class PydanticDeprecatedSince29(DeprecationWarning): ...
class PydanticDeprecatedSince210(DeprecationWarning): ...
class PydanticDeprecatedSince211(DeprecationWarning): ...
class PydanticDeprecatedSince212(DeprecationWarning): ...
class PydanticDeprecationWarning(DeprecationWarning): ...
class PydanticExperimentalWarning(DeprecationWarning): ...

# annotated handlers
class GetCoreSchemaHandler: ...
class GetJsonSchemaHandler: ...

# pydantic_core re-exports
class ValidationError(Exception): ...
class ValidationInfo: ...
class SerializationInfo: ...
class ValidatorFunctionWrapHandler: ...
class FieldSerializationInfo: ...
class SerializerFunctionWrapHandler: ...
class OnErrorOmit: ...
