/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

use std::path::Path;
use std::path::PathBuf;

use anyhow::Result;
use pyrefly_python::module_name::ModuleName;
use ruff_python_ast::Mod;
use ruff_python_ast::ModModule;
use ruff_python_ast::PySourceType;
use ruff_python_parser::ParseOptions;

use crate::pyrefly::sys_info::PythonVersion;
use crate::runner::default_python_version;
use crate::runner::to_ruff_version;

// Operations on a single module, either .py or .pyi

/// Result of parsing a Python module in string form into an AST.
pub struct ParsedModule {
    pub name: ModuleName,
    pub ast: ModModule,
    pub source_type: PySourceType,
    /// Whether this module came from an `__init__.py` file.
    /// Affects relative import resolution: in `__init__.py`, `.foo` resolves
    /// relative to the current package rather than the parent package.
    pub is_init: bool,
    /// Whether the source file is old-style Thrift codegen (ttypes.py).
    /// These modules are treated as safe (all effects removed) during analysis.
    pub is_thrift_generated: bool,
    /// Sorted array of all of the byte positions of line numbers.
    newline_positions: Vec<u32>,
}

impl ParsedModule {
    pub fn is_stub(&self) -> bool {
        self.source_type == PySourceType::Stub
    }

    pub fn byte_to_line_number(&self, pos: u32) -> usize {
        let idx = match self.newline_positions.binary_search(&pos) {
            Ok(n) => n,
            Err(n) => n,
        };

        // Check if we're out-of-bounds which implies it's on the last line, or there's no newlines
        // at all and there's only one line.
        let size = self.newline_positions.len();
        if size == 0 {
            return 1;
        } else if idx >= size {
            return size + 1;
        }

        let newline_pos = self.newline_positions[idx];

        // Add 1 to go from 0-indexed to 1-indexed, then might have to add another to account for
        // how the line is _after_ the newline.
        if pos <= newline_pos { idx + 1 } else { idx + 2 }
    }
}

pub fn file_source_type(path: &Path) -> Option<PySourceType> {
    match path.extension().and_then(|e| e.to_str()) {
        Some("py") => Some(PySourceType::Python),
        Some("pyi") => Some(PySourceType::Stub),
        _ => None,
    }
}

fn is_thrift_generated(source: &str) -> bool {
    let prefix = source.get(..256).unwrap_or(source);
    prefix.contains("Autogenerated by Thrift") && prefix.contains(concat!("@", "generated"))
}

pub fn parse_file(
    source: &str,
    typ: PySourceType,
    name: ModuleName,
    is_init: bool,
) -> ParsedModule {
    parse_file_with_version(source, typ, name, is_init, default_python_version())
}

pub fn parse_file_with_version(
    source: &str,
    typ: PySourceType,
    name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> ParsedModule {
    // Use Python version to support `lazy` keyword
    let options = ParseOptions::from(typ).with_target_version(to_ruff_version(&version));
    let res = ruff_python_parser::parse_unchecked(source, options);
    let newline_positions = compute_newline_positions(source);
    let Mod::Module(ast) = res.into_syntax() else {
        unreachable!("PySourceType::Python and ::Stub always produce Mod::Module")
    };
    let is_thrift = typ == PySourceType::Python
        && name.as_str().ends_with(".ttypes")
        && is_thrift_generated(source);
    ParsedModule {
        name,
        ast,
        source_type: typ,
        is_init,
        is_thrift_generated: is_thrift,
        newline_positions,
    }
}

pub fn parse_source(source: &str, module_name: ModuleName, is_init: bool) -> ParsedModule {
    parse_file(source, PySourceType::Python, module_name, is_init)
}

pub fn parse_source_with_version(
    source: &str,
    module_name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> ParsedModule {
    parse_file_with_version(source, PySourceType::Python, module_name, is_init, version)
}

pub fn parse_pyi(source: &str, module_name: ModuleName, is_init: bool) -> ParsedModule {
    parse_file(source, PySourceType::Stub, module_name, is_init)
}

pub fn parse_pyi_with_version(
    source: &str,
    module_name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> ParsedModule {
    parse_file_with_version(source, PySourceType::Stub, module_name, is_init, version)
}

pub fn read_and_parse_source(
    path: &PathBuf,
    module_name: ModuleName,
    is_init: bool,
) -> Result<ParsedModule> {
    read_and_parse_source_with_version(path, module_name, is_init, default_python_version())
}

pub fn read_and_parse_source_with_version(
    path: &PathBuf,
    module_name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> Result<ParsedModule> {
    // Handle non-utf-8 encodings via lossy conversion.
    let bytes = std::fs::read(path)?;
    let source = String::from_utf8_lossy(&bytes);
    Ok(parse_source_with_version(
        &source,
        module_name,
        is_init,
        version,
    ))
}

/// Given the text contents of a file, compute a sorted array of byte positions where all the
/// line numbers are.
fn compute_newline_positions(source: &str) -> Vec<u32> {
    source
        .chars()
        .enumerate()
        .filter_map(|(index, ch)| (ch == '\n').then_some(index as u32))
        .collect::<Vec<_>>()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_parsed(source: &str) -> ParsedModule {
        parse_source(source, ModuleName::from_str("test"), false)
    }

    #[test]
    fn empty_file() {
        let m = make_parsed("");
        assert_eq!(m.byte_to_line_number(0), 1, "empty file returns line 1");
    }

    #[test]
    fn single_line_no_newline() {
        let m = make_parsed("hello");
        assert_eq!(m.byte_to_line_number(0), 1, "position 0 is on line 1");
        assert_eq!(m.byte_to_line_number(3), 1, "position 3 is on line 1");
        assert_eq!(m.byte_to_line_number(4), 1, "position 4 is on line 1");
    }

    #[test]
    fn position_at_newline_boundary() {
        // "ab\ncd\n" -> newlines at positions 2 and 5
        let m = make_parsed("ab\ncd\n");
        assert_eq!(m.byte_to_line_number(2), 1, "at first newline");
        assert_eq!(m.byte_to_line_number(5), 2, "at second newline");
    }

    #[test]
    fn position_past_eof() {
        // "a\nb\n" -> newlines at positions 1 and 3
        let m = make_parsed("a\nb\n");
        assert_eq!(m.newline_positions.len(), 2);
        // Past EOF returns one line past the last newline
        assert_eq!(
            m.byte_to_line_number(100),
            3,
            "past EOF returns last line number"
        );
    }

    #[test]
    fn multi_line_various_positions() {
        // "line1\nline2\nline3"
        // newlines at positions 5 and 11
        let m = make_parsed("line1\nline2\nline3");
        assert_eq!(m.byte_to_line_number(0), 1, "start of line 1");
        assert_eq!(m.byte_to_line_number(4), 1, "end of line 1 content");
        assert_eq!(m.byte_to_line_number(5), 1, "at first newline");
        assert_eq!(m.byte_to_line_number(6), 2, "start of line 2");
        assert_eq!(m.byte_to_line_number(11), 2, "at second newline");
        // Positions past the last newline are on the last line
        assert_eq!(m.byte_to_line_number(12), 3, "start of line 3");
        assert_eq!(m.byte_to_line_number(16), 3, "end of file");
    }
}
