name: lifeguard
on:
  push:
    paths:
      - '**/*'
      - '!.*'
      - '.github/workflows/lifeguard.yml'
  pull_request:
  schedule:
    - cron: '0 12 * * 1' # 12pm Monday

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2026-02-28
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: lifeguard
    - run: cargo fmt -- --check
    - run: cargo clippy --release
    - run: cargo test --release
    - run: cargo build --bin lifeguard --release
